name: PR Revision

on:
  pull_request:
    branches:
      - develop  # Trigger on PR targeting the 'develop' branch

permissions:
  contents: write  # Allow writing to the repository (necessary for posting comments)
  pull-requests: write  # Allow posting comments on PRs

jobs:
  setup-java:
    runs-on: ubuntu-latest  # Specify the OS environment for the job

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Fetch the PR code

      - name: Set up JDK (Java 17)
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Specify the Java version to use
          distribution: 'temurin'  # Java distribution (Temurin is a popular open-source JDK)

      - name: Run Linter (Gradle)
        run: ./gradlew lint  # Run linting for your Android project using Gradle

  lint-report:
    runs-on: ubuntu-latest  # Specify the OS environment for the job

    needs: setup-java  # Ensure this step only runs after the setup-java job has completed

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Fetch the PR code

      - name: Reviewdog Lint Report
        uses: reviewdog/action-reviewdog@v1  # Use the correct Reviewdog action
        with:
          reviewdog_version: latest
          github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
          reporter: github-pr-review  # This will post comments directly on the PR
          check_name: "Android Lint"  # Optional: Name for the check
          lint_command: 'cat app/build/reports/lint-results.xml'  # Read lint results file
          lint_format: 'checkstyle'  # Specify Checkstyle format for Reviewdog
