name: PR Revision

on:
  pull_request:
    branches:
      - develop  # Trigger on PR targeting the 'develop' branch

jobs:
  setup-java:
    runs-on: ubuntu-latest  # Specify the OS environment for the job

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Fetch the PR code

      - name: Set up JDK (Java 17)
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Specify the Java version to use
          distribution: 'temurin'  # Java distribution (Temurin is a popular open-source JDK)

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Clean Build (Ensure directory exists)
        run: ./gradlew clean  # Clean the build to ensure a fresh run

      - name: Run Gradle build
        run: ./gradlew build

      - name: Run Linter (Gradle)
        run: ./gradlew lint  # Run linting for your Android project using Gradle
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          lint_xml_file: app/build/reports/lint-results.xml
