name: Android Lint

on:
  pull_request:
    branches:
      - develop  # Run this workflow when a PR is opened against the 'develop' branch

jobs:
  lint-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Check out the repository

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # Use the Temurin JDK distribution

      - name: Run Android Lint
        run: ./gradlew lint  # Run the Android lint task

      - name: Post Android Lint Results
        uses: marcelkliemannel/android-lint-action@v1  # Use the Android Lint GitHub Action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Token for posting PR comments
          lint_report_path: 'app/build/reports/lint-results.xml'  # Path to the lint results
