name: PR Revision

on:
  pull_request:
    branches:
      - develop  # Trigger on pull requests targeting the 'develop' branch

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # Specify the required distribution

      - name: Run Linter
        run: ./gradlew lint

      - name: Report Lint Issues to PR
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          filter_mode: added  # Only comment on changes in the PR
