name: Android Lint

on:
  pull_request:
    branches:
      - develop  # Run this workflow for PRs targeting 'develop'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Check out the PR branch

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Android Lint
        run: ./gradlew lint  # Run the Android lint task

      - name: Verify Lint Report Path
        run: ls -R app/build/reports/lint-results.xml  # Ensure the lint report exists

      - name: Set up Reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest  # Install Reviewdog

      - name: Post Lint Results with Reviewdog
        run: |
          reviewdog -f=checkstyle \
            -name="Android Lint" \
            -reporter=github-pr-review \
            -level=error \
            < app/build/reports/lint-results.xml
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
