name: PR Revision

on:
  pull_request:
    branches:
      - develop  # Trigger on PR targeting the 'develop' branch

jobs:
  setup-java:
    runs-on: ubuntu-latest  # Specify the OS environment for the job

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Fetch the PR code

      - name: Set up JDK (Java 17)
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Specify the Java version to use
          distribution: 'temurin'  # Java distribution (Temurin is a popular open-source JDK)

      - name: Run Linter (Gradle)
        run: ./gradlew lint  # Run linting for your Android project using Gradle

  lint-report:
    runs-on: ubuntu-latest  # Specify the OS environment for the job

    needs: setup-java  # Ensure this step only runs after the setup-java job has completed

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Fetch the PR code

      - name: Report Lint Issues to PR (Reviewdog)
        uses: reviewdog/action-checkstyle@v1  # Use the Reviewdog action for Checkstyle (supports Android linting)
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
          reporter: github-pr-review  # This will post comments directly on the PR
          lint_file: build/reports/lint-results.xml  # Path to lint results file generated by Gradle
